from pathlib import Path
import subprocess

import numpy as np
import pandas as pd


# ============================================================
# RETAIL SALES PERFORMANCE ANALYTICS
# Phase 14 — Step 6
# SQL vs Python Cross-Validation
#
# File:
# src/analysis/sql_python_validation.py
#
# Purpose:
# Compare all 32 approved KPI results between:
#   1. Python KPI calculations
#   2. PostgreSQL SQL calculations
#
# Output:
# reports/business_metrics/sql_python_validation.csv
#
# PostgreSQL:
#   - ONE psql execution
#   - ONE password prompt
#
# Validation:
#   - Absolute tolerance = 1e-6
#   - Relative tolerance = 1e-9
# ============================================================


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

REPORT_DIR = (
    PROJECT_ROOT
    / "reports"
    / "business_metrics"
)

OUTPUT_FILE = (
    REPORT_DIR
    / "sql_python_validation.csv"
)


# ============================================================
# DATABASE CONFIGURATION
# ============================================================

PSQL_PATH = (
    r"C:\Program Files\PostgreSQL\18\bin\psql.exe"
)

DATABASE = "retail_sales_analytics"
DB_USER = "postgres"


# ============================================================
# VALIDATION SETTINGS
# ============================================================

ABSOLUTE_TOLERANCE = 1e-6
RELATIVE_TOLERANCE = 1e-9


# ============================================================
# APPROVED KPI INVENTORY
# ============================================================

EXPECTED_KPIS = [
    "Total Revenue",
    "Total Orders",
    "Average Order Value",
    "Monthly Revenue Growth",
    "Total Customers",
    "Repeat Customer Rate",
    "On-Time Delivery Rate",
    "Average Delivery Time",
    "Average Review Score",
    "Total Order Value",
    "Monthly Revenue",
    "Average Items per Order",
    "Customer Lifetime Revenue",
    "Average Customer Order Value",
    "Category Revenue",
    "Category Revenue Share",
    "Product Revenue",
    "Seller Revenue",
    "Seller Order Count",
    "Revenue by Customer State",
    "Total Payment Value",
    "Payment Method Share",
    "Average Payment Installments",
    "Average Processing Time",
    "Late Delivery Rate",
    "Average Delivery Difference",
    "Total Freight Value",
    "Low Satisfaction Rate",
    "High Satisfaction Rate",
    "Rolling 3-Month Revenue",
    "Multi-Payment Order Rate",
    "Freight-to-Price Ratio",
]


# ============================================================
# REQUIRED FILE CHECK
# ============================================================

def require_file(path):
    """
    Ensure a required file exists.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Required file not found:\n{path}"
        )


# ============================================================
# LOAD PYTHON KPI RESULTS
# ============================================================

def load_python_results():
    """
    Load KPI results generated by kpi_calculations.py.
    """

    path = REPORT_DIR / "kpi_results.csv"

    require_file(path)

    df = pd.read_csv(path)

    required_columns = [
        "kpi_name",
        "kpi_value",
        "kpi_hierarchy",
    ]

    missing = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            "Python KPI results missing columns: "
            + ", ".join(missing)
        )

    # --------------------------------------------------------
    # Check duplicate KPI names
    # --------------------------------------------------------

    duplicates = df["kpi_name"].duplicated()

    if duplicates.any():

        duplicate_names = (
            df.loc[
                duplicates,
                "kpi_name"
            ]
            .tolist()
        )

        raise ValueError(
            "Duplicate KPI names found in "
            "Python results:\n"
            + "\n".join(duplicate_names)
        )

    # --------------------------------------------------------
    # Check missing approved KPIs
    # --------------------------------------------------------

    available_kpis = set(df["kpi_name"])

    missing_kpis = [
        kpi
        for kpi in EXPECTED_KPIS
        if kpi not in available_kpis
    ]

    if missing_kpis:

        raise ValueError(
            "Missing Python KPI(s):\n"
            + "\n".join(missing_kpis)
        )

    return df


# ============================================================
# SQL QUERY
# ============================================================

SQL_QUERY = r"""

WITH
-- ==========================================================
-- MONTHLY REVENUE
-- ==========================================================

monthly_revenue AS (

    SELECT
        year_month,
        SUM(order_revenue) AS revenue

    FROM validation.orders_features

    WHERE year_month IS NOT NULL

    GROUP BY year_month

),

monthly_growth AS (

    SELECT
        year_month,
        revenue,

        LAG(revenue)
        OVER (
            ORDER BY year_month
        ) AS previous_revenue

    FROM monthly_revenue

),

monthly_growth_values AS (

    SELECT

        CASE

            WHEN previous_revenue IS NULL
                 OR previous_revenue = 0

            THEN NULL

            ELSE
                (
                    (
                        revenue
                        - previous_revenue
                    )
                    / previous_revenue
                ) * 100

        END AS growth

    FROM monthly_growth

),

monthly_rolling AS (

    SELECT

        year_month,

        SUM(revenue)
        OVER (
            ORDER BY year_month
            ROWS BETWEEN 2 PRECEDING
                     AND CURRENT ROW
        ) AS rolling_3_month_revenue

    FROM monthly_revenue

),


-- ==========================================================
-- CUSTOMER FEATURES
--
-- Used for:
--   - Repeat Customer Rate
--   - Average Customer Order Value
--
-- Customer Lifetime Revenue is intentionally NOT taken from
-- customer_features because the Python KPI calculates it
-- directly from orders grouped by customer_unique_id.
-- ==========================================================

customer_features AS (

    SELECT

        customer_unique_id,

        customer_order_count,

        repeat_customer_flag,

        average_customer_order_value

    FROM validation.customer_features

),


-- ==========================================================
-- CUSTOMER LIFETIME REVENUE
--
-- This reproduces the Python KPI definition:
--
-- 1. Group orders by customer_unique_id
-- 2. Sum order_revenue for each customer
-- 3. Average those customer-level revenues
--
-- This must be calculated from orders_features rather than
-- relying on a precomputed customer feature column.
-- ==========================================================

customer_lifetime_revenue AS (

    SELECT

        customer_unique_id,

        SUM(order_revenue)
            AS customer_revenue

    FROM validation.orders_features

    WHERE customer_unique_id IS NOT NULL

    GROUP BY customer_unique_id

),


-- ==========================================================
-- CATEGORY REVENUE
-- ==========================================================

category_revenue AS (

    SELECT

        p.product_category_name
            AS product_category,

        SUM(oi.item_revenue)
            AS revenue

    FROM validation.order_items_features oi

    LEFT JOIN cleaned.products p

        ON oi.product_id = p.product_id

    GROUP BY
        p.product_category_name

),


-- ==========================================================
-- PRODUCT REVENUE
-- ==========================================================

product_revenue AS (

    SELECT

        product_id,

        SUM(item_revenue)
            AS revenue

    FROM validation.order_items_features

    WHERE product_id IS NOT NULL

    GROUP BY product_id

),


-- ==========================================================
-- SELLER REVENUE
-- ==========================================================

seller_revenue AS (

    SELECT

        seller_id,

        SUM(item_revenue)
            AS revenue

    FROM validation.order_items_features

    WHERE seller_id IS NOT NULL

    GROUP BY seller_id

),


-- ==========================================================
-- SELLER ORDER COUNT
-- ==========================================================

seller_orders AS (

    SELECT

        seller_id,

        COUNT(DISTINCT order_id)
            AS order_count

    FROM validation.order_items_features

    WHERE seller_id IS NOT NULL

    GROUP BY seller_id

),


-- ==========================================================
-- REGIONAL REVENUE
-- ==========================================================

state_revenue AS (

    SELECT

        c.customer_state,

        SUM(o.order_revenue)
            AS revenue

    FROM validation.orders_features o

    LEFT JOIN cleaned.customers c

        ON o.customer_id = c.customer_id

    GROUP BY
        c.customer_state

)


-- ==========================================================
-- 32 KPI RESULTS
-- ==========================================================


SELECT
    'Total Revenue' AS kpi_name,
    SUM(order_revenue)::numeric AS kpi_value

FROM validation.orders_features


UNION ALL


SELECT
    'Total Orders',
    COUNT(DISTINCT order_id)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Average Order Value',

    (
        SUM(order_revenue)
        /
        NULLIF(
            COUNT(DISTINCT order_id),
            0
        )
    )::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Monthly Revenue Growth',
    AVG(growth)::numeric

FROM monthly_growth_values


UNION ALL


SELECT
    'Total Customers',
    COUNT(DISTINCT customer_unique_id)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Repeat Customer Rate',

    (
        AVG(
            repeat_customer_flag::numeric
        )
    ) * 100

FROM customer_features


UNION ALL


SELECT
    'On-Time Delivery Rate',

    (
        COUNT(*) FILTER (
            WHERE delivery_difference_days <= 0
        )::numeric
        /
        NULLIF(
            COUNT(*) FILTER (
                WHERE delivery_difference_days IS NOT NULL
            ),
            0
        )
    ) * 100

FROM validation.orders_features


UNION ALL


SELECT
    'Average Delivery Time',
    AVG(delivery_time_days)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Average Review Score',
    AVG(review_score)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Total Order Value',
    SUM(total_order_value)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Monthly Revenue',
    AVG(revenue)::numeric

FROM monthly_revenue


UNION ALL


SELECT
    'Average Items per Order',
    AVG(items_per_order)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Customer Lifetime Revenue',

    AVG(customer_revenue)::numeric

FROM customer_lifetime_revenue


UNION ALL


SELECT
    'Average Customer Order Value',

    AVG(average_customer_order_value)::numeric

FROM customer_features


UNION ALL


SELECT
    'Category Revenue',
    AVG(revenue)::numeric

FROM category_revenue


UNION ALL


SELECT
    'Category Revenue Share',

    (
        MAX(revenue)
        /
        NULLIF(
            SUM(revenue),
            0
        )
    ) * 100

FROM category_revenue


UNION ALL


SELECT
    'Product Revenue',
    AVG(revenue)::numeric

FROM product_revenue


UNION ALL


SELECT
    'Seller Revenue',
    AVG(revenue)::numeric

FROM seller_revenue


UNION ALL


SELECT
    'Seller Order Count',
    AVG(order_count)::numeric

FROM seller_orders


UNION ALL


SELECT
    'Revenue by Customer State',
    AVG(revenue)::numeric

FROM state_revenue


UNION ALL


SELECT
    'Total Payment Value',
    SUM(payment_value_per_order)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Payment Method Share',
    NULL::numeric


UNION ALL


SELECT
    'Average Payment Installments',
    AVG(number_payment_installments)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Average Processing Time',
    AVG(processing_time_days)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Late Delivery Rate',

    (
        COUNT(*) FILTER (
            WHERE delivery_difference_days > 0
        )::numeric
        /
        NULLIF(
            COUNT(*) FILTER (
                WHERE delivery_difference_days IS NOT NULL
            ),
            0
        )
    ) * 100

FROM validation.orders_features


UNION ALL


SELECT
    'Average Delivery Difference',
    AVG(delivery_difference_days)::numeric

FROM validation.orders_features


UNION ALL


SELECT
    'Total Freight Value',
    SUM(freight_value)::numeric

FROM validation.order_items_features


UNION ALL


SELECT
    'Low Satisfaction Rate',

    (
        COUNT(*) FILTER (
            WHERE review_score <= 2
        )::numeric
        /
        NULLIF(
            COUNT(*) FILTER (
                WHERE review_score IS NOT NULL
            ),
            0
        )
    ) * 100

FROM validation.orders_features


UNION ALL


SELECT
    'High Satisfaction Rate',

    (
        COUNT(*) FILTER (
            WHERE review_score >= 4
        )::numeric
        /
        NULLIF(
            COUNT(*) FILTER (
                WHERE review_score IS NOT NULL
            ),
            0
        )
    ) * 100

FROM validation.orders_features


UNION ALL


SELECT
    'Rolling 3-Month Revenue',

    (
        SELECT
            rolling_3_month_revenue

        FROM monthly_rolling

        ORDER BY year_month DESC

        LIMIT 1
    )::numeric


UNION ALL


SELECT
    'Multi-Payment Order Rate',

    (
        COUNT(*) FILTER (
            WHERE multi_payment_flag = 1
        )::numeric
        /
        NULLIF(
            COUNT(*) FILTER (
                WHERE multi_payment_flag IS NOT NULL
            ),
            0
        )
    ) * 100

FROM validation.orders_features


UNION ALL


SELECT
    'Freight-to-Price Ratio',
    AVG(freight_to_price_ratio)::numeric

FROM validation.order_items_features


ORDER BY kpi_name;

"""


# ============================================================
# EXECUTE SQL
# ============================================================

def calculate_sql_kpis():
    """
    Execute all 32 SQL KPI calculations in ONE PostgreSQL call.

    PostgreSQL will therefore request the password only once.
    """

    psql = Path(PSQL_PATH)

    if not psql.exists():

        raise FileNotFoundError(
            "PostgreSQL psql executable not found:\n"
            f"{PSQL_PATH}"
        )

    command = [
        PSQL_PATH,
        "-U",
        DB_USER,
        "-d",
        DATABASE,
        "-A",
        "-t",
        "-F",
        "|",
        "-c",
        SQL_QUERY,
    ]

    print(
        "\nExecuting SQL validation query..."
    )

    completed = subprocess.run(
        command,
        capture_output=True,
        text=True,
    )

    if completed.returncode != 0:

        raise RuntimeError(
            "SQL execution failed:\n"
            + completed.stderr.strip()
        )

    results = {}

    for line in completed.stdout.splitlines():

        line = line.strip()

        if not line:
            continue

        parts = line.split("|", 1)

        if len(parts) != 2:
            continue

        kpi_name = parts[0].strip()
        raw_value = parts[1].strip()

        if (
            raw_value == ""
            or raw_value.lower() == "null"
        ):

            value = np.nan

        else:

            try:

                value = float(raw_value)

            except ValueError as exc:

                raise ValueError(
                    f"Invalid SQL value for "
                    f"{kpi_name}: {raw_value}"
                ) from exc

        results[kpi_name] = value

    # --------------------------------------------------------
    # Check missing SQL KPIs
    # --------------------------------------------------------

    missing = [
        kpi
        for kpi in EXPECTED_KPIS
        if kpi not in results
    ]

    if missing:

        raise ValueError(
            "SQL result missing KPI(s):\n"
            + "\n".join(missing)
        )

    # --------------------------------------------------------
    # Check unexpected SQL KPIs
    # --------------------------------------------------------

    unexpected = [
        kpi
        for kpi in results
        if kpi not in EXPECTED_KPIS
    ]

    if unexpected:

        raise ValueError(
            "Unexpected SQL KPI(s):\n"
            + "\n".join(unexpected)
        )

    return results


# ============================================================
# NUMERIC DIFFERENCE
# ============================================================

def numeric_difference(
    sql_value,
    python_value
):
    """
    Calculate absolute difference.
    """

    if (
        pd.isna(sql_value)
        and pd.isna(python_value)
    ):

        return np.nan

    if (
        pd.isna(sql_value)
        or pd.isna(python_value)
    ):

        return np.nan

    return abs(
        float(sql_value)
        -
        float(python_value)
    )


# ============================================================
# VALUE MATCH
# ============================================================

def values_match(
    sql_value,
    python_value
):
    """
    Determine whether SQL and Python values match
    within controlled tolerance.
    """

    # Both NULL / NaN.
    if (
        pd.isna(sql_value)
        and pd.isna(python_value)
    ):

        return True

    # Only one NULL / NaN.
    if (
        pd.isna(sql_value)
        or pd.isna(python_value)
    ):

        return False

    return bool(
        np.isclose(
            float(sql_value),
            float(python_value),
            atol=ABSOLUTE_TOLERANCE,
            rtol=RELATIVE_TOLERANCE,
        )
    )


# ============================================================
# CREATE VALIDATION REPORT
# ============================================================

def create_validation_report(
    python_results,
    sql_results
):
    """
    Compare all SQL and Python KPI values.
    """

    rows = []

    python_lookup = (
        python_results
        .set_index(
            "kpi_name"
        )[
            "kpi_value"
        ]
        .to_dict()
    )

    for kpi_name in EXPECTED_KPIS:

        python_value = pd.to_numeric(
            python_lookup[kpi_name],
            errors="coerce"
        )

        sql_value = sql_results[
            kpi_name
        ]

        difference = numeric_difference(
            sql_value,
            python_value
        )

        status = (
            "PASS"
            if values_match(
                sql_value,
                python_value
            )
            else "FAIL"
        )

        rows.append(
            [
                kpi_name,
                sql_value,
                python_value,
                difference,
                status,
            ]
        )

    return pd.DataFrame(
        rows,
        columns=[
            "KPI Name",
            "SQL Result",
            "Python Result",
            "Absolute Difference",
            "Validation Status",
        ]
    )


# ============================================================
# VALIDATE REPORT
# ============================================================

def validate_report(validation):
    """
    Validate all 32 KPI comparisons.
    """

    expected_count = len(
        EXPECTED_KPIS
    )

    if len(validation) != expected_count:

        raise ValueError(
            f"Expected {expected_count} "
            f"validation rows, "
            f"found {len(validation)}."
        )

    failed = validation[
        validation[
            "Validation Status"
        ] != "PASS"
    ]

    if not failed.empty:

        print(
            "\nWARNING: KPI validation failures detected:"
        )

        print(
            failed.to_string(
                index=False
            )
        )

        raise ValueError(
            f"{len(failed)} KPI "
            f"validation(s) failed."
        )


# ============================================================
# MAIN
# ============================================================

def main():

    print(
        "============================================================"
    )

    print(
        "Phase 14 — Step 6"
    )

    print(
        "SQL vs Python Cross-Validation"
    )

    print(
        "============================================================"
    )

    REPORT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------
    # Load Python results
    # --------------------------------------------------------

    print(
        "\nLoading Python KPI results..."
    )

    python_results = (
        load_python_results()
    )

    print(
        f"Python KPIs loaded: "
        f"{len(python_results)}"
    )

    # --------------------------------------------------------
    # SQL results
    # --------------------------------------------------------

    print(
        "\nCalculating SQL reference values..."
    )

    print(
        "NOTE: PostgreSQL will prompt "
        "for the password once."
    )

    sql_results = (
        calculate_sql_kpis()
    )

    print(
        f"SQL KPIs calculated: "
        f"{len(sql_results)}"
    )

    # --------------------------------------------------------
    # Create validation report
    # --------------------------------------------------------

    print(
        "\nCreating validation report..."
    )

    validation = (
        create_validation_report(
            python_results,
            sql_results
        )
    )

    # --------------------------------------------------------
    # Validate
    # --------------------------------------------------------

    print(
        "Validating results..."
    )

    validate_report(
        validation
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    validation.to_csv(
        OUTPUT_FILE,
        index=False
    )

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    pass_count = (
        validation[
            "Validation Status"
        ]
        == "PASS"
    ).sum()

    fail_count = (
        validation[
            "Validation Status"
        ]
        == "FAIL"
    ).sum()

    print(
        "\n============================================================"
    )

    print(
        "Phase 14 — Step 6 Complete"
    )

    print(
        "============================================================"
    )

    print(
        f"KPIs Validated: {len(validation)}"
    )

    print(
        f"PASS: {pass_count}"
    )

    print(
        f"FAIL: {fail_count}"
    )

    print(
        "Validation Status: PASS"
    )

    print(
        f"Output: {OUTPUT_FILE}"
    )

    print(
        f"Tolerance: "
        f"absolute={ABSOLUTE_TOLERANCE}, "
        f"relative={RELATIVE_TOLERANCE}"
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()