-- ============================================================
-- Phase 8 — Step 8.8
-- SQL Analytical Output Exports
-- ============================================================

\copy (SELECT d.year, d.month, d.month_name, ROUND(SUM(oi.price), 2) AS monthly_sales, COUNT(DISTINCT oi.order_id) AS orders, COUNT(*) AS order_items FROM analytics.fact_order_items oi INNER JOIN analytics.dim_date d ON oi.order_date_key = d.date_key GROUP BY d.year, d.month, d.month_name ORDER BY d.year, d.month) TO 'reports/sql/analytical_outputs/monthly_sales.csv' WITH CSV HEADER;

\copy (SELECT COALESCE(p.product_category_name_english, p.product_category_name, 'Unknown') AS category, COUNT(*) AS units_sold, COUNT(DISTINCT oi.order_id) AS orders, ROUND(SUM(oi.price), 2) AS sales, ROUND(100.0 * SUM(oi.price) / SUM(SUM(oi.price)) OVER (), 2) AS sales_contribution_pct FROM analytics.fact_order_items oi INNER JOIN analytics.dim_product p ON oi.product_key = p.product_key GROUP BY COALESCE(p.product_category_name_english, p.product_category_name, 'Unknown') ORDER BY sales DESC) TO 'reports/sql/analytical_outputs/category_sales.csv' WITH CSV HEADER;

\copy (SELECT p.product_id, COALESCE(p.product_category_name_english, p.product_category_name, 'Unknown') AS category, COUNT(*) AS units_sold, COUNT(DISTINCT oi.order_id) AS orders, ROUND(SUM(oi.price), 2) AS sales, RANK() OVER (PARTITION BY COALESCE(p.product_category_name_english, p.product_category_name, 'Unknown') ORDER BY SUM(oi.price) DESC) AS category_rank FROM analytics.fact_order_items oi INNER JOIN analytics.dim_product p ON oi.product_key = p.product_key GROUP BY p.product_id, COALESCE(p.product_category_name_english, p.product_category_name, 'Unknown') ORDER BY category, category_rank, p.product_id) TO 'reports/sql/analytical_outputs/product_ranking.csv' WITH CSV HEADER;

\copy (SELECT s.seller_id, s.seller_city, s.seller_state, COUNT(*) AS units_sold, COUNT(DISTINCT oi.order_id) AS orders, ROUND(SUM(oi.price), 2) AS sales, ROUND(SUM(oi.freight_value), 2) AS freight, ROUND(AVG(oi.price), 2) AS average_item_price FROM analytics.fact_order_items oi INNER JOIN analytics.dim_seller s ON oi.seller_key = s.seller_key GROUP BY s.seller_id, s.seller_city, s.seller_state ORDER BY sales DESC) TO 'reports/sql/analytical_outputs/seller_performance.csv' WITH CSV HEADER;

\copy (SELECT s.seller_state AS state, COUNT(DISTINCT oi.order_id) AS orders, COUNT(*) AS units_sold, ROUND(SUM(oi.price), 2) AS sales, ROUND(SUM(oi.freight_value), 2) AS freight FROM analytics.fact_order_items oi INNER JOIN analytics.dim_seller s ON oi.seller_key = s.seller_key GROUP BY s.seller_state ORDER BY sales DESC) TO 'reports/sql/analytical_outputs/regional_sales.csv' WITH CSV HEADER;

\copy (WITH customer_sales AS (SELECT o.customer_key, COUNT(DISTINCT o.order_id) AS orders, ROUND(SUM(oi.price), 2) AS sales FROM analytics.fact_orders o INNER JOIN analytics.fact_order_items oi ON o.order_id = oi.order_id GROUP BY o.customer_key) SELECT c.customer_id, c.customer_city, c.customer_state, COALESCE(cs.orders, 0) AS orders, COALESCE(cs.sales, 0) AS sales, CASE WHEN COALESCE(cs.orders, 0) > 1 THEN 'Repeat' WHEN COALESCE(cs.orders, 0) = 1 THEN 'Single' ELSE 'No Orders' END AS customer_type FROM analytics.dim_customer c LEFT JOIN customer_sales cs ON c.customer_key = cs.customer_key ORDER BY sales DESC, orders DESC) TO 'reports/sql/analytical_outputs/customer_metrics.csv' WITH CSV HEADER;

\copy (SELECT payment_type, payment_installments, COUNT(*) AS payment_records, COUNT(DISTINCT order_id) AS orders, ROUND(SUM(payment_value), 2) AS payment_value FROM analytics.fact_payments GROUP BY payment_type, payment_installments ORDER BY payment_value DESC) TO 'reports/sql/analytical_outputs/payment_analysis.csv' WITH CSV HEADER;

\copy (SELECT CASE WHEN delivered.full_date > estimated.full_date THEN 'Late' ELSE 'On Time / Early' END AS delivery_status, COUNT(*) AS orders, ROUND(AVG(delivered.full_date - purchase.full_date), 2) AS average_delivery_days, ROUND(AVG(delivered.full_date - estimated.full_date), 2) AS average_estimate_variance_days FROM analytics.fact_orders o INNER JOIN analytics.dim_date purchase ON o.purchase_date_key = purchase.date_key INNER JOIN analytics.dim_date delivered ON o.delivered_customer_date_key = delivered.date_key INNER JOIN analytics.dim_date estimated ON o.estimated_delivery_date_key = estimated.date_key WHERE o.delivered_customer_date_key IS NOT NULL AND o.estimated_delivery_date_key IS NOT NULL GROUP BY CASE WHEN delivered.full_date > estimated.full_date THEN 'Late' ELSE 'On Time / Early' END ORDER BY delivery_status) TO 'reports/sql/analytical_outputs/delivery_analysis.csv' WITH CSV HEADER;